namespace AQMod.Assets.Textures
{
    public enum GlowID : ushort
    {
        DemonicEnergy = 0,
        PotionofBussrushium = 1,
        OrganicEnergy = 2,
        VortexBlowpipe = 3,
        MagmalbulbiaStaff = 4,
        MonoxideHat = 5,
        MonoxideHatItem = 6,
        PentalScythe = 7,
        CosmicEnergy = 8,
        AquaticEnergy = 9,
        LotusStaff = 10,
        MonoxiderStaff = 11,
        StaffofSwiftness = 12,
        StaffofIronskin = 13,
        CorruptHellSword = 14,
        GlimmeringStatue = 15,
        CorruptHellYoyo = 16,
        AlphaCenfuryItem = 17,
        NarrenBolt = 18,
        EqualizedPrism = 19,
        EqualizedPrism2 = 20,
        StaffofNightVision = 21,
        StariteBlade = 22,
        SolYoyo = 23,
        Nova = 24,
        UltimateSword = 25,
        AtmosphericEnergy = 26,
        NeutronJuice = 27,
        HorizonSkies = 28,
        FrigidTwilightProjectile = 29,
        Devwand = 30,
        SignofPatience = 31,
        SignofJustice = 32,
        StaffofRegeneration = 33,
        UltimateEnergy = 34,
        SpaceShot = 35,
        AtmosphericEnergyAprilFools = 36,
        MagicWand = 37,
        HorizonLine = 38,
        ArachnotronLeg = 39,
        ArachnotronLeg2 = 40,
        Globebulb = 41,
        UltimateEnergy2 = 42,
        SpectralLens = 43,
        OmegaStariteMask = 44,
        OmegaStariteMaskItem = 45,
        MysteryGrail = 46,
        StaffofWaterBreathing = 47,
        BatonofNightVision = 48,
        CelestialRod = 49,
        BatonofRage = 50,
        BatonofWrath = 51,
        Raygun = 52,
        MoonlightWall = 53,
        MoonlightWallWall = 54,
        XenonBasher = 55,
        StariteStaff = 56,
        Burnterizer = 57,
        Count
    }
}