namespace Aequu2.Core.UI;

public class InterfaceLayerNames {
    public const string InterfaceLogic1_0 = "Vanilla: Interface Logic 1";
    public const string MultiplayerPlayerNames_1 = "Vanilla: MP Player Names";
    public const string EmoteBubbles_2 = "Vanilla: Emote Bubbles";
    public const string EntityMarkers_3 = "Vanilla: Entity Markers";
    public const string SmartCursorTargets_4 = "Vanilla: Smart Cursor Targets";
    public const string LaserRuler_5 = "Vanilla: Laser Ruler";
    public const string Ruler_6 = "Vanilla: Ruler";
    public const string GamepadLockOn_7 = "Vanilla: Gamepad Lock On";
    public const string TileGridOption_8 = "Vanilla: Tile Grid Option";
    public const string TownNPCHouseBanners_9 = "Vanilla: Town NPC House Banners";
    public const string HideUIToggle_10 = "Vanilla: Hide UI Toggle";
    public const string WireSelection_11 = "Vanilla: Wire Selection";
    public const string CaptureManagerCheck_12 = "Vanilla: Capture Manager Check";
    public const string IngameOptions_13 = "Vanilla: Ingame Options";
    public const string FancyUI_14 = "Vanilla: Fancy UI";
    public const string AchievementCompletePopups_15 = "Vanilla: Achievement Complete Popups";
    public const string EntityHealthBars_16 = "Vanilla: Entity Health Bars";
    public const string InvasionProgressBars_17 = "Vanilla: Invasion Progress Bars";
    public const string MapMinimap_18 = "Vanilla: Map / Minimap";
    public const string DiagnoseNet_19 = "Vanilla: Diagnose Net";
    public const string DiagnoseVideo_20 = "Vanilla: Diagnose Video";
    public const string SignTileBubble_21 = "Vanilla: Sign Tile Bubble";
    public const string HairWindow_22 = "Vanilla: Hair Window";
    public const string DresserWindow_23 = "Vanilla: Dresser Window";
    public const string NPCSignDialog_24 = "Vanilla: NPC / Sign Dialog";
    public const string InterfaceLogic2_25 = "Vanilla: Interface Logic 2";
    public const string ResourceBars_26 = "Vanilla: Resource Bars";
    public const string InterfaceLogic3_27 = "Vanilla: Interface Logic 3";
    public const string Inventory_28 = "Vanilla: Inventory";
    public const string InfoAccessoriesBar_29 = "Vanilla: Info Accessories Bar";
    public const string SettingsButton_30 = "Vanilla: Settings Button";
    public const string Hotbar_31 = "Vanilla: Hotbar";
    public const string BuildersAccessoriesBar_32 = "Vanilla: Builder Accessories Bar";
    public const string RadialHotbars_33 = "Vanilla: Radial Hotbars";
    public const string MouseText_34 = "Vanilla: Mouse Text";
    public const string PlayerChat_35 = "Vanilla: Player Chat";
    public const string Cursor_36 = "Vanilla: Cursor";
    public const string MouseItemOrNPCHead_37 = "Vanilla: Mouse Item / NPC Head";
    public const string MouseOver_38 = "Vanilla: Mouse Over";
    public const string InteractItemIcon_39 = "Vanilla: Interact Item Icon";
    public const string InterfaceLogic4_40 = "Vanilla: Interface Logic 4";
}