namespace Aequus.Core.UI;

public class InterfaceLayerNames {
    public const System.String InterfaceLogic1_0 = "Vanilla: Interface Logic 1";
    public const System.String MultiplayerPlayerNames_1 = "Vanilla: MP Player Names";
    public const System.String EmoteBubbles_2 = "Vanilla: Emote Bubbles";
    public const System.String EntityMarkers_3 = "Vanilla: Entity Markers";
    public const System.String SmartCursorTargets_4 = "Vanilla: Smart Cursor Targets";
    public const System.String LaserRuler_5 = "Vanilla: Laser Ruler";
    public const System.String Ruler_6 = "Vanilla: Ruler";
    public const System.String GamepadLockOn_7 = "Vanilla: Gamepad Lock On";
    public const System.String TileGridOption_8 = "Vanilla: Tile Grid Option";
    public const System.String TownNPCHouseBanners_9 = "Vanilla: Town NPC House Banners";
    public const System.String HideUIToggle_10 = "Vanilla: Hide UI Toggle";
    public const System.String WireSelection_11 = "Vanilla: Wire Selection";
    public const System.String CaptureManagerCheck_12 = "Vanilla: Capture Manager Check";
    public const System.String IngameOptions_13 = "Vanilla: Ingame Options";
    public const System.String FancyUI_14 = "Vanilla: Fancy UI";
    public const System.String AchievementCompletePopups_15 = "Vanilla: Achievement Complete Popups";
    public const System.String EntityHealthBars_16 = "Vanilla: Entity Health Bars";
    public const System.String InvasionProgressBars_17 = "Vanilla: Invasion Progress Bars";
    public const System.String MapMinimap_18 = "Vanilla: Map / Minimap";
    public const System.String DiagnoseNet_19 = "Vanilla: Diagnose Net";
    public const System.String DiagnoseVideo_20 = "Vanilla: Diagnose Video";
    public const System.String SignTileBubble_21 = "Vanilla: Sign Tile Bubble";
    public const System.String HairWindow_22 = "Vanilla: Hair Window";
    public const System.String DresserWindow_23 = "Vanilla: Dresser Window";
    public const System.String NPCSignDialog_24 = "Vanilla: NPC / Sign Dialog";
    public const System.String InterfaceLogic2_25 = "Vanilla: Interface Logic 2";
    public const System.String ResourceBars_26 = "Vanilla: Resource Bars";
    public const System.String InterfaceLogic3_27 = "Vanilla: Interface Logic 3";
    public const System.String Inventory_28 = "Vanilla: Inventory";
    public const System.String InfoAccessoriesBar_29 = "Vanilla: Info Accessories Bar";
    public const System.String SettingsButton_30 = "Vanilla: Settings Button";
    public const System.String Hotbar_31 = "Vanilla: Hotbar";
    public const System.String BuildersAccessoriesBar_32 = "Vanilla: Builder Accessories Bar";
    public const System.String RadialHotbars_33 = "Vanilla: Radial Hotbars";
    public const System.String MouseText_34 = "Vanilla: Mouse Text";
    public const System.String PlayerChat_35 = "Vanilla: Player Chat";
    public const System.String Cursor_36 = "Vanilla: Cursor";
    public const System.String MouseItemOrNPCHead_37 = "Vanilla: Mouse Item / NPC Head";
    public const System.String MouseOver_38 = "Vanilla: Mouse Over";
    public const System.String InteractItemIcon_39 = "Vanilla: Interact Item Icon";
    public const System.String InterfaceLogic4_40 = "Vanilla: Interface Logic 4";
}